import { StyleSheet, Platform } from 'react-native';

const PRIMARY_BLUE = '#5B9BFF';
const DARK_BLUE = '#2E5AA8';
const SUCCESS_GREEN = '#2ECC71';
const WARNING_ORANGE = '#F39C12';
const ERROR_RED = '#E74C3C';
const LIGHT_BG = '#F8FAFC';
const CARD_WHITE = '#FFFFFF';
const TEXT_DARK = '#1E293B';
const TEXT_LIGHT = '#64748B';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: LIGHT_BG,
  },
  emergencyContainer: {
    backgroundColor: '#FFEBEE',
  },
  header: {
    backgroundColor: CARD_WHITE,
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 50 : 30,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  emergencyHeader: {
    backgroundColor: '#FF4444',
  },
  appTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: DARK_BLUE,
    textAlign: 'center',
  },
  emergencyTitle: {
    color: '#FFFFFF',
    fontSize: 24,
  },
  subtitle: {
    fontSize: 14,
    color: TEXT_LIGHT,
    textAlign: 'center',
    marginTop: 4,
    fontWeight: '500',
  },
  timerContainer: {
    backgroundColor: CARD_WHITE,
    margin: 16,
    marginTop: 12,
    marginBottom: 8,
    padding: 16,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
    alignItems: 'center',
  },
  timerCompleted: {
    backgroundColor: SUCCESS_GREEN,
  },
  timerWarning: {
    backgroundColor: WARNING_ORANGE,
  },
  emergencyTimer: {
    backgroundColor: '#FF4444',
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  sosActive: {
    backgroundColor: '#FF6B6B',
    borderWidth: 3,
    borderColor: '#E74C3C',
  },
  timerLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: TEXT_LIGHT,
    marginBottom: 8,
  },
  timerText: {
    fontSize: 42,
    fontWeight: '800',
    color: TEXT_DARK,
    letterSpacing: 2,
  },
  timerStatus: {
    fontSize: 14,
    fontWeight: '600',
    color: TEXT_LIGHT,
    marginTop: 8,
  },
  sosWarningText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FFFFFF',
    marginTop: 8,
    textAlign: 'center',
  },
  emergencyHelpText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    marginTop: 8,
    textAlign: 'center',
  },
  flashingBanner: {
    backgroundColor: '#FF6B6B',
    padding: 12,
    marginHorizontal: 16,
    marginBottom: 8,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  flashingBannerText: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 16,
    textAlign: 'center',
  },
  mapContainer: {
    flex: 1,
    marginHorizontal: 16,
    marginBottom: 16,
    marginTop: 8,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
    backgroundColor: '#E2E8F0',
    minHeight: 200,
  },
  map: {
    width: '100%',
    height: '100%',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: TEXT_LIGHT,
    fontWeight: '500',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FEF2F2',
    padding: 20,
  },
  errorIcon: {
    fontSize: 48,
    marginBottom: 16,
  },
  errorTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: ERROR_RED,
    marginBottom: 8,
  },
  errorText: {
    fontSize: 14,
    color: TEXT_LIGHT,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 20,
  },
  retryButton: {
    backgroundColor: PRIMARY_BLUE,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
  },
  retryButtonText: {
    color: CARD_WHITE,
    fontWeight: '600',
    fontSize: 16,
  },
  markerContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  markerPulse: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(91, 155, 255, 0.3)',
    position: 'absolute',
  },
  emergencyPulse: {
    backgroundColor: 'rgba(255, 68, 68, 0.3)',
  },
  markerPin: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: PRIMARY_BLUE,
    borderWidth: 3,
    borderColor: CARD_WHITE,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  emergencyMarker: {
    backgroundColor: '#FF4444',
  },
  markerDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: CARD_WHITE,
  },
  centerButton: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: CARD_WHITE,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  centerButtonText: {
    fontSize: 20,
  },
  locationCard: {
    position: 'absolute',
    top: 16,
    left: 16,
    right: 16,
    backgroundColor: CARD_WHITE,
    padding: 16,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  locationTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: TEXT_DARK,
    marginBottom: 4,
  },
  locationCoordinates: {
    fontSize: 14,
    color: TEXT_LIGHT,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    marginBottom: 4,
  },
  locationStatus: {
    fontSize: 12,
    color: SUCCESS_GREEN,
    fontWeight: '600',
  },
  actionsContainer: {
    flexDirection: 'row',
    gap: 16,
    padding: 16,
    backgroundColor: CARD_WHITE,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
  },
  sosButton: {
    width: 90,
    height: 56,
    borderRadius: 28,
    backgroundColor: ERROR_RED,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  emergencySOSButton: {
    backgroundColor: '#FF6B6B',
  },
  disabledButton: {
    backgroundColor: '#95a5a6',
    opacity: 0.6,
  },
  sosText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 18,
  },
  arrivedButton: {
    flex: 1,
    height: 56,
    borderRadius: 14,
    backgroundColor: SUCCESS_GREEN,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  emergencyStopButton: {
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#FF4444',
  },
  arrivedText: {
    color: '#0b3d1a',
    fontWeight: '800',
    fontSize: 16,
  },
  emergencyStopText: {
    color: '#FF4444',
  },
  emergencyTimer: {
  backgroundColor: '#dc2626',
  borderColor: '#dc2626',
},
  movementStatus: {
    padding: 12,
    marginHorizontal: 20,
    marginBottom: 10,
    borderRadius: 10,
    backgroundColor: '#e8f5e8',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#4CAF50',
  },
  movementStatusWarning: {
    backgroundColor: '#fff3cd',
    borderColor: '#ffc107',
  },
  movementStatusAlert: {
    backgroundColor: '#f8d7da',
    borderColor: '#dc3545',
  },
  movementStatusText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#155724',
  },
});
